### ISSUE TITLE
IPの再生成 に失敗する

### ISSUE THREAD

**Issue by fujimaya** [ciniml/atom_display_fpga#1]
恐れ入ります。
README 記載の手順を進めていたところ「IPの再生成」の箇所でエラーが出ておりました。
> Unknown UP type, Please check your IP Configu file.
IPC file device information is lost.

（私の環境での固有の問題でしたら申し訳ないです）

ダウンロード可能だった、Gowin V1.9.8.09 を使用しているのですが、
EDA に SDRAM_controller_top_SIP と sdram_rpll の IP が存在しない？ため、Select IP Config file から該当 ipc を開いてもエラーになっているかと思われました。

何か回避方法などあったりしますでしょうか...？
ご確認を頂けますと幸いです。

**Comment by ciniml** [comment]
ご連絡ありがとうございます。最近ビルドしてなかったので最新版でビルドできるか確認してみます。

**Comment by ciniml** [comment]
返信が遅くなりすみません。一応確認なのですが、このときのGOWIN EDAはStandard版とEducation版のどちらでしょうか？

ATOM Displayで使われているデバイスは、 GW1NR-LV9QN88C6/I5 であり、Education版ではサポートしていません。

(ややこしいですが、 Tang Nano 9Kのデバイスは GW1NR-LV9QN88 **P** C6/I5 で、内蔵メモリがPSRAMになっています。)

現在手元のGOWIN EDAのStandard版ライセンスが切れており、V1.9.8.09で合成できない状況ですので、ライセンス更新出来次第、V1.9.8.09 Standard でも確認してみようと思います。

**Comment by fujimaya** [comment]
ご確認ありがとうございます。
Education版を使用しておりました。

> Education版ではサポートしていません

なんと...そうだったのですね、、
私の確認不足、認識不足のため、お手数をお掛けしてしまい誠に申し訳ございません。。

**Comment by ciniml** [comment]
ちなみにライセンス申請自体はGOWINのサイトから結構簡単にできるので、もしご興味おありでしたら、Standard版ライセンス申請して試していただくと良いかと思います。

フォームに必要事項を入力して送信すれば、1日くらいでメールにライセンスが添付されてきます。 (昨日申請して今朝とどきました)

https://www.gowinsemi.com/ja/support/license/
