### ISSUE TITLE
640x480 output resolution does not work

### ISSUE THREAD

**Issue by SinanAkkoyun** [ciniml/atom_display_fpga#2]
Hello dear ciniml,
thank you so much for coding this product, I can not thank you enough, it is so awesome! 
Thank you for your time.

When I do this call with M5GFX:

`M5AtomDisplay display(640, 360, 60, 640, 360);`

I do not get any HDMI output. Also not with 640x480 (which is what I need)

It seems that every aspect ratio other than 16:9 is not working. I need the 640x480 aspect ratio to work for an AR glass micro oled... Is there a way to incorporate that resolution?

Again, thank you very much, I appreciate it a lot!

**Comment by lovyan03** [comment]
@SinanAkkoyun 
Since you have specified a height of 360, the M5GFX would only output that way.
You can try the following code.
```
M5AtomDisplay display(640, 480, 60, 640, 480);
```

The pixel clock is fixed at 74.25 MHz, so the blanking period is very long.
If your display device supports this, setting the refresh rate to a value higher than 60 may stabilize it.


ciniml created the FPGA design, but not the M5GFX.
I think he is having trouble with this Issue.

**Comment by ciniml** [comment]
Hi.

As @lovyan03 said, ATOM Display currently only supports 74.25[MHz] pixel clock, which is optimal for generating 1280x720 60Hz video signal.
ATOM Display can generate video signals for other resolutions by changing video parameters (blanking timings), which is actually out of some video signal standards like CVT.

If your AR glass supports 1280x960 60Hz  signal, you can try the parameter below to initialize M5GFX.

```c
M5AtomDisplay display(640, 480, 60, 1280, 960);
```

If your AR glass does not support it, it requires to change FPGA design.
In order to support lower resolutions with optimal pixel clock (e.g. 640x480 requires  25.175[MHz]), the FPGA design must be changed to generate such pixel clock.

If you want to try it, I can provde experimental FPGA design and test code with PlatformIO.

**Comment by SinanAkkoyun** [comment]
Hello, thank you both for assessing my issue and for the quick response!

@lovyan03  Thank you for the suggestion, but I already tried to set the output and input resolution to 640x480 and unfortunately nothing that results in an output resolution other than 16:9 works. More specifically, with 'not working' I mean no output at all, as if I'd power the display driver without HDMI cable connected.

@ciniml 
Thank you so much for the quick response! I've tried the resolution you gave me but it results in the same behaviour as described above, just no HDMI signal. 

Below I gave some details into my experimenting...

I would be super grateful if you could maybe implement a 640x480 mode if you don't mind and adapt the FPGA clock dividers for the pixel clock, that would be super kind of you! I would be very happy about that, thank you so so much for not only providing the FPGA design but also for helping me out!!

<details>
  <summary>If this is any help, here are some further observations of mine</summary>
I've tried many resolutions and this is my finding:
All example resolutions 'worked' (resulted in HDMI output) except for the 1920x1080. (1280, 720/960, 540/640, 360/320, 180)
As soon as I change the resolution to be something else, it appears as if the device does not receive HDMI at all.

Regarding which resolutions the AR glasses display support: I really don't know. On a PC HDMI output, I can set the output to many resolutions and most of them 'work'. The display kind of adapts on the fly, when I for example supply a 1920x1080 resolution, the display glitches at the right and bottom, the displayed picture slowly stretches, then tiles (as in repeats itself along the vertical axis) and after some seconds it stabilises to a tiled and stretched view of the 1920x1080 image. The stretching is not really to compensate for the aspect ratio difference, it's much more and weird.
But with the Atom Lite Display, it behaves quite a bit differently. As soon as it's not 16:9, the output doesn't work at all, this is why I suspected it had something to do with the FPGA, because the display doesn't receive any signal at all as it seems.

When at for example 1280x720 with the Atom Lite Display, the display works very good, but the image is stretched (this time by the correct factor of adapting 1280x720 to 640x480) and a small horizontal slice is being cut from the top of the image and put at the bottom (with the triangle test, the tip is being cut off and placed at the bottom of the screen)
</details>

**Comment by lovyan03** [comment]
@SinanAkkoyun 
Signals in resolutions other than 16:9 can be output, and output of 640x480 signals has actually been confirmed to work.
However, since the signal is out of standard, it may not be displayed depending on the reception capability of the display device.

![image](https://user-images.githubusercontent.com/42724151/211710582-ef5f5a8e-6a28-4f99-80fd-021f8960c76c.png)

https://user-images.githubusercontent.com/42724151/211710517-c003a69e-2b6c-45d1-a45b-ed9b6b94b50a.MP4

We have no idea of the specifications of your display unit. Do you have the model number or product description URL information?

**Comment by ciniml** [comment]
@SinanAkkoyun 

Hi.

I've pushed experimental version of FPGA design and its test code to [resolution_640x480 branch](https://github.com/ciniml/atom_display_fpga/tree/resolution_640x480).

You can try it by building test code located in the [test directory](https://github.com/ciniml/atom_display_fpga/tree/resolution_640x480/test) 

Pre-generated FPGA bitstream is already in the repository, so all you have to do is just configure the serial port in `platformio.ini` and run `make` at the `test` directory.

**Comment by SinanAkkoyun** [comment]
Hi!
@lovyan03 Thank you very much for reassuring that the module does output at that resolutions! Sure, the display itself is ECX336CN, here is a link to the full module: https://www.alibaba.com/product-detail/Brand-new-0-23-inch-micro_1600454239323.html

@ciniml Thank you so much for writing the code and changing the design! I tried the code (ran make in advance and flashed the code) and it did not work, I checked if the 1280x720 resolution works and it does. Again, no output.

The display module itself has 640x400 pixels but my windows and raspberry pi HDMI out tests had the best luck with working at 640x480, but even then the aspect ratio is not quite right.
However, would it please be possible to try to adapt the FPGA to output 640x400 resolution with the correct timings? I would be super grateful about that and thank you again so much for helping me! :)

**Comment by lovyan03** [comment]
@SinanAkkoyun 
There is one important thing to note.
The FPGA is written only the first time after power-on.
This means that once you have written the new code to ATOM, you will need to unplug the USB cable and turn the power back on.

If this does not work, it would be helpful if you could read the EDID information for the display.
Since the ATOM Display does not have the ability to read the EDID, you will need to use other means.

**Comment by SinanAkkoyun** [comment]
Thank you for the note, I wasn't aware of that, but after following the advice it still didn't work, but I believe this could be due to the 640x400 resolution

Sure! here is what I received from `xrandr --prop | edid-decode`
```
edid-decode (hex):
 
00 ff ff ff ff ff ff 00 3d 85 30 d2 00 00 00 00
13 1f 01 00 80 02 01 a0 2a cf 74 a3 57 4c b0 23
09 48 4c 20 00 00 01 01 01 01 01 01 01 01 01 01
01 01 01 01 01 01 8c 0a 80 da 20 90 7d 10 60 40
f6 0c 80 90 21 00 00 1e 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 0a 20 20 20 20 20 20 00 b1
 
----------------
 
Block 0, Base EDID:
  EDID Structure Version & Revision: 1.0
  Vendor & Product Identification:
    Manufacturer: OLE
    Model: 53808
    Made in: week 19 of 2021
  Basic Display Parameters & Features:
    Digital display
    Maximum image size: 2 cm x 1 cm
    Gamma: 2.60
    DPMS levels: Off
    RGB color display
    First detailed timing is the preferred timing
  Color Characteristics:
    Red  : 0.6396, 0.3398
    Green: 0.2998, 0.6904
    Blue : 0.1376, 0.0380
    White: 0.2822, 0.2968
  Established Timings I & II:
    DMT 0x04:   640x480    59.940 Hz   4:3    31.469 kHz  25.175 MHz
  Standard Timings: none
  Detailed Timing Descriptors:
    DTD 1:   640x400    59.940 Hz   8:5    31.469 kHz  27.000 MHz (640 mm x 400 mm)
                 Hfront   96 Hsync  64 Hback  58 Hpol P
                 Vfront   63 Vsync   6 Vback  56 Vpol P
    Empty Descriptor
    Empty Descriptor
    Manufacturer-Specified Display Descriptor (0x00): 00 00 00 00 00 00 00 00 00 0a 20 20 20 20 20 20 '..........      '
Checksum: 0xb1
```

**Comment by SinanAkkoyun** [comment]
I need to add that the "Established Timings" only rocks a resolution of 640x480 because I set the Raspberry Pi up to that resolution (because 640x400 with default timings wasn't working)

Using this tool https://www.epanorama.net/faq/vga2rgb/calc.html (because I know knowthing about video) and providing the parameters form the EDID, I calculated my new modeline to be: `Modeline "640x400"   27   640 736 800 858   400 463 469 525  +hsync +vsync`

However, either the modeline calculation is wrong or the display driver won't accept it's specified resolution, because as soon as I switch to that new mode, the display glitches again (it shows the scene two times, stretched and twice across the y axis, when it reaches that position it stays stable as two views of the same image + some white flickering lines at the bottom and right)

**Comment by SinanAkkoyun** [comment]
Hello, I got my hands on the timing specs
![Alibaba1658165](https://user-images.githubusercontent.com/43215895/212014390-e6cfd52f-e579-4514-864e-01f65bdec124.png)

The only problem is I didn't get them to work with my windows PC nor with my raspberry pi. They result in the same duplicated glitched view. When inputting these timings with CRU, the vertical front porch of 87 was too high and I couldnt enter it in (the max allowed was 62)

After I realized that the 640x400 resolution doesn't work anywhere on no device I contacted the reseller.
If it is no big deal, would it be possible to implement those timings? Otherwise I totally understand if that's too much work for not knowing the result.

Thank you very much for helping

**Comment by ciniml** [comment]
@SinanAkkoyun 

Hi.

I've updated the FPGA design and test code to output 640x400 59.94Hz video signal with 27[MHz] pixel clock.

I've confirmed that my ATOM Display output 640x400 video signal and my display (Mitsubishi RDT234WX) can show this (though the output is a bit blured horizontally).

![image](https://user-images.githubusercontent.com/7610112/212136113-da7191e6-d666-4213-95e8-8b71c994d2be.png)

I hope it helps you.

**Comment by SinanAkkoyun** [comment]
@ciniml 
Hey!
Thank you so much! Unfortunately, now my display doesn't accept any resolution at all with the new code...
I even added these video timings as per screenshot I uploaded:

...src/lgxf/v1/panel/Panel_M5HDMI.cpp inserted at line 499
```cpp
    vt.h.front_porch = 96;
    vt.h.back_porch = 58;
    vt.h.active = 640;
    vt.h.sync = 64;

    vt.v.front_porch = 87;
    vt.v.back_porch = 32;
    vt.v.active = 400;
    vt.v.sync = 6;
```
(at the moment I only have access to my laptop, so no external display, but I think the FPGA itself works because when I flash the normal library it works again)

Is there any chance that we could still get this to work? I really don't know why the display is acting as if there was no video signal at all, it at least detects (but glitchy) every resolution when connected to my laptop...

**Comment by ciniml** [comment]
@SinanAkkoyun 

The experimental FPGA design does not accept any video parameter settings from ESP32. The parameter is hard coded in the FPGA design

Currently the FPGA design uses the video parameter in the screen shot of the SONY image sensor datasheet.

https://github.com/ciniml/atom_display_fpga/blob/resolution_640x480/atom_display/src/main/scala/system/m5stackhdmi.scala#L53

So, if this design does not work for your AR glass, I think that it is not a video timing problem but a electrical signal compatibility problem.

**Comment by SinanAkkoyun** [comment]
@ciniml 
Thank you for the response.

But I do not understand how that could be an electrical signal compatibility problem, because with the normal FPGA setup at 1280x720 it works? (I mean it detects, still stretched and the top is at the bottom as described earlier)

When I tried to enter these SONY video timings in CRU on windows (custom resolution utility), it threw me an error that the vertcial front porch of 87 is way too high. I also tried to set the exact timings on a raspberry pi and there it also just glitches and duplicates the image. Maybe the timings on the sheet are wrong? They actually differ from the EDID

I contacted the reseller, he assured me that on his unit and windows PC it works fine, I kindly asked him if he could provide the exact timings via installing CRU, I hope he can do that and I hope that they will work on my devices. If it's not working on any device of mine at 640x400, I do not want to waste your time with experimenting with different parameters now if the SONY timings don't work, except you maybe have another idea why this doesn't work?

I appreciate your help and support so so much! Thank you again, I will keep you posted on the timings and hopefully this time it will work! ^^

**Comment by lovyan03** [comment]
@SinanAkkoyun 
hello.
We have updated the **develop** branch for both M5GFX and LovyanGFX since @ciniml has implemented the pixel clock change feature.
The pixel clock can be specified when creating the instance.

https://github.com/m5stack/M5GFX/blob/develop/docs/ATOMDisplay.md

![image](https://user-images.githubusercontent.com/42724151/213909126-dbb31e19-7b58-49ae-b17b-09a6a4b19160.png)

Please experiment again with this. It may be possible to display the resolution that did not work correctly in the recent experiment.

probabry, this.
```
M5AtomDisplay display ( 640, 400, 60, 640, 400, 1, 1, 27000000 );
```

**Comment by SinanAkkoyun** [comment]
@lovyan03 
Hello!
Thank you so much, that is very nice of you!

I finally received the CRU display timings screenshot from the Alibaba supplier. Sadly and confusingly, these timings seem to work for them (or they didn't realize that they didn't choose that profile?) but not for me (I mean even windows wise).

Here are the timings:

![WhatsApp Image 2023-02-03 at 18 33 55](https://user-images.githubusercontent.com/43215895/216669508-db6a8f4f-fa36-4b9d-b344-34d63cabe0b4.jpeg)


My question is the following:
Could you please implement these timings above in the branch? 
> The experimental FPGA design does not accept any video parameter settings from ESP32. The parameter is hard coded in the FPGA design

I will experiment with the new code, my last exam is in a couple of days, after that I will have tested the new code.

Thank you both so much for all the support and actions, I am super thankful! :)

**Comment by SinanAkkoyun** [comment]
Maybe you can help me with this and know what might be going wrong

Here is an image, these timings result in black bars:
![WhatsApp Image 2023-02-03 at 18 47 35](https://user-images.githubusercontent.com/43215895/216672187-6f898383-5859-41d1-b2c2-a677f8e8786b.jpeg)


Do you both perhaps know what about the HDMI settings causes this?
Sorry, I'm no expert by any means, but the driver somehow finds it's way to a stable sync between hdmi and display output, meaning when a wrong resolution is applied, you can see how it syncs after time, either resulting in one image or in glitchy multiple ones (if that information helps by any means). Also, the resolution I showed on top sometimes results in a stable image but if a wrong resolution has been applied before while on power, the resolution above results in multiple images

Maybe you know what causes the black bars, thank you!

**Comment by SinanAkkoyun** [comment]
Hi again!
I'm sorry for all the confusion. The supplier, after a month of contacting, just admitted / realized that he has the exact same problem and spread misinformation before, every driver board has this issue of 640x400 not working.

That's such a bummer. Nonetheless, I will absolutely test the 640x480 with the new pixel clock update and will try to unstretch myself :)

**Comment by SinanAkkoyun** [comment]
Hey! I tried many different combinations, but it still just won't work / won't display anything on the screen.

From your suggested 640x400x60@27 to this
`M5AtomDisplay display(640, 480, 60, 640, 480, 1, 1, 25175000);`
Nothing seems to work. Only the standard resolutions for example `M5AtomDisplay display(1280, 720, 60, 1280, 720, 1, 1, 74250000);` work...

Thank you for the help

**Comment by SinanAkkoyun** [comment]
Hm, given the 640x480 will never work, could you please help me fixing a half working resolution?

1280x720 is working but wrapping at the end
![20230222_022418](https://user-images.githubusercontent.com/43215895/220496920-04dd0fc1-3887-4bb7-91e1-65880ae2814c.jpg)
You can see, that the top of the image is cut off and transported to the bottom, while inserting a black block inbetween. How can we change it so that the image is not wrapping?
I'd say this is easier to achieve. If that works I can close the issue, that would be very kind

**Comment by SinanAkkoyun** [comment]
(I guess for such occasions it would be awesome if one could specify all timing parameters (porch etc) manually)

**Comment by lovyan03** [comment]
@SinanAkkoyun 

Please try this and see.
Set the resolution when the instance is created to match the active resolution of the timing parameter
```cpp
M5AtomDisplay display(640,400,60,640,400,1,1,27000000);

void setup(void)
{
  display.init();
  auto panel = (lgfx::Panel_M5HDMI*)display.getPanel();
  lgfx::Panel_M5HDMI::video_timing_t param;
  param.h.active = 640;
  param.h.front_porch = 96;
  param.h.sync = 64;
  param.h.back_porch = 58;
  param.v.active = 400;
  param.v.front_porch = 63;
  param.v.sync = 6;
  param.v.back_porch = 56;
  panel->setVideoTiming(&param);
}
```

**Comment by SinanAkkoyun** [comment]
@lovyan03 THANK YOU! ^^ Wow, it finally works!
I still have visual glitches but no more than with a laptop, so the chip does exactly what it's supposed to do, thank you both so so much! <3

**Comment by SinanAkkoyun** [comment]
Hello, there is one more thing: Why does this line appear?
```cpp
M5AtomDisplay display(640,480,60,640,480,1,1,25175000);
display.init();
  auto panel = (lgfx::Panel_M5HDMI*)display.getPanel();
  lgfx::Panel_M5HDMI::video_timing_t param;
  param.h.active = 640;
  param.h.front_porch = 16;
  param.h.sync = 96;
  param.h.back_porch = 48;
  param.v.active = 480;
  param.v.front_porch = 10;
  param.v.sync = 2;
  param.v.back_porch = 33;
  panel->setVideoTiming(&param);
```
![image](https://user-images.githubusercontent.com/43215895/221279932-636c9a09-e317-4f9a-9507-e4389fc5337c.png)
(it's hard to see but there is a horizontal white line where normally a black bar should be at the bottom of the screen)

With these timings, my windows laptop lets the bar on the bottom be black. With this chip, the black bar contains a one pixel line at the bottom. Is there a way around that?

**Comment by SinanAkkoyun** [comment]
Correction: in windows it uses the full resolution. On here, when I let a line scan the display, I can see that the dispay does now show pixels that are drawn at the beginning of the screen vertically

**Comment by lovyan03** [comment]
@SinanAkkoyun 
umm,, I can't get an accurate picture of the situation from the text and its pictures.
If possible, I would like you to try the display on both your AR glasses and your PC display. And let me know what the differences are.
Sorry for the hassle, but please provide the following
 - Buildable test code (including drawing process)
 - Photographic and graphic illustration of actual display results

**Comment by SinanAkkoyun** [comment]
Sure! Here is the code:
```cpp

M5AtomDisplay display(640,480,60,640,480,10,0.2,25175000);

void setup(void)
{
  display.init();
  auto panel = (lgfx::Panel_M5HDMI*)display.getPanel();
  lgfx::Panel_M5HDMI::video_timing_t param;
  param.h.active = 640;
  param.h.front_porch = 16;
  param.h.sync = 96;
  param.h.back_porch = 48;
  param.v.active = 480;
  param.v.front_porch = 10;
  param.v.sync = 2;
  param.v.back_porch = 33;
  panel->setVideoTiming(&param);

  display.begin();
  display.startWrite();
}
```
Just init and do nothing.

Here is a picture of it:
![image](https://user-images.githubusercontent.com/43215895/221401579-530dddc0-6951-4904-8e96-f39c5f811f7b.png)

And here is a graphical representation:
![image](https://user-images.githubusercontent.com/43215895/221401607-6552e971-51c1-4bee-b69e-e2d122066c2e.png)


Here goes an image with an explanation:
![image](https://user-images.githubusercontent.com/43215895/221401685-3e6c00ba-80b3-4b07-b78c-afaa5cd82599.png)
The screen itself is 640x400 (cyan border, so the whole picture), but the display driver is badly designed in a way that 640x400 crt resolution doesn't work and 640x480 resolution doesn't fill up the whole screen (only dark green area). This results in a black bar at the bottom. Now however, when connecting the display to any other machine (PC etc), the black bar stays completely black. On your FPGA hdmi board, a white line exists in the black bar (even though I am not drawing anything).

For reference, here is a white windows screen:
![image](https://user-images.githubusercontent.com/43215895/221401885-4a00d747-f26f-478e-a2d6-6ea612a512cc.png)
One can see the black bar, but in windows it stays black.

I hope this is conclusive, thank you for your help :)

**Comment by lovyan03** [comment]
I built and ran the source code as you presented it.
On my PC monitor, I get a completely black screen.
The signal information on the monitor shows 640x480 @59Hz.

I would guess that your AR Glass symptom is that it is out of sync and is displaying something off-screen.
If the line is the result of something outside the active area being displayed, I don't know how to fix it.
If anything, that is not an ATOMDisplay defect, but a defect in the AR glasses.

Try adding the following lines A rectangle will appear around the perimeter of the active area.
```
  display.drawRect(0, 0, display.width(), display.height(), TFT_WHITE);
```

If something appears outside the bounds of this rectangle, the reason for it is not clear to us.



By the way, your constructor has a strange use of arguments.
If the display magnification is unknown, specify 0. It will be calculated automatically.
```cpp
M5AtomDisplay display(
    640,      // int   logical width
    480,      // int   logical height
    60,       // float refresh rate
    640,      // int   output width
    480,      // int   output height
    0,        // int ★★ X Display Magnification
    0,        // int ★★ Y Display Magnification
    25175000  // int   request pixel clock
    );
```

Also, the following two lines of your sample code are not necessary
```
  display.begin();
  display.startWrite();
```

**Comment by SinanAkkoyun** [comment]
Hello, thank you for the quick response.
I did the magnification to 0 on purpose, I was testing streching correction before (640,400,60,640,480,0,0,...) but the automatic scaling just doesn't work.

But regarding the white line, this must be some kind of implementation issue with the FPGA, because the windows black bar is always completely black (also RPI).
The same occurs at 1270x720. Although I am a complete noob in the HDMI protocol, I believe it has something to do with the HDMI timings or how you fill the blanking periods or something like that?


However, to be honest that is an issue that is supposedly much harder to debug, so here is my current issue which is the most important for me:
The scaling does not work. As I described before, the bad driver board stretches the 640x480 to 640x400. However, when I initialize the display with the virtual resolution of 640x400, it does not correct the stretching, circles and rectangles are stretched as before.
I'd like to correct for the stretching at GFX library level, but no matter which virtual resolution I set, it doesn't stretch properly (for example I only see an effect at 640x200, nothing at 640x400) and no matter what I set the scale to (6th and 7th parameters) it doesn't change anything.

How can I force the scaling to be x: 1, y: 1.2? (or something to correct for the 640x480 to 640x400 mismatch)

**Comment by lovyan03** [comment]
Only integer scaling factors can be set for scaling.
There is no floating point adjustment function.

**Comment by SinanAkkoyun** [comment]
Ahh I see, is there some way to add 1.2 y scaling so that circles, texts etc can be drawn correctly? Or is a PR for that required?

**Comment by SinanAkkoyun** [comment]
Anyways, I can work around that and do a PR when I'm done with correcting the primitives. But is there a way to fix the white line problem? To my eyes the only possible way of fixing that would be some kind of wrong blanking period signal? Idk, thank you very much!

**Comment by lovyan03** [comment]
There are no plans to support floating point magnification.
Frankly, that is a feature that is not needed if the video is displayed correctly.
We don't want to devote the resources to address special situations.

Assuming that the blanking period signal is misidentified as an active period, the line may be an audio signal.
Since it uses a common code with ModuleDisplay, the ATOMDisplay output signal also contains silent audio information.

**Comment by ciniml** [comment]
@SinanAkkoyun  I thought that you've confirmed your display works with the video timing parameter which @lovyan03 provides at this reply https://github.com/ciniml/atom_display_fpga/issues/2#issuecomment-1444029953

I am not sure why you are trying to use the VIDEO parameter with a resolution of 640x480.
I assume that 640x480 and 1280x720 resolutions are not supported by your panel?

The white line at the bottom of the screen is probably because your display does not support these resolutions and is failing to detect the VSYNC signal, resulting in incorrect vertical synchronization.

**Comment by SinanAkkoyun** [comment]
@ciniml No, all screen driver boards are sadly poorly built and are not able to output 640x400 correctly, that's why I need to resort to 640x480 stretched.
Nonetheless, the display, as I described, "only" supports those resolutions and they work without white lines on windows.

@lovyan03 Ah, I see, is there a way to disable them?

I will implement "anti aliasing" floating point based interpolation on my own, but what I can't fix are the white lines, I'd be super grateful if you could help me fix em :)

**Comment by lovyan03** [comment]
If the parameters are entered as per the EDID and it still does not display correctly, then I believe it is a defect in the product.

**Comment by SinanAkkoyun** [comment]
> If the parameters are entered as per the EDID and it still does not display correctly, then I believe it is a defect in the product.

I don't know how to test that, the product doesn't show lines in the black bar region on any other HDMI port I've tried

**Comment by SinanAkkoyun** [comment]
I will close this issue, thank you so much for all the great help, I appreciate it so much!
